Update to NixOS 22.11
The following changes were needed for this update to even build:

- LESSCHARSET doesn't belong in the i18n locale variables, it's simply an
  environment variable. It fixes this error for `glibc-locales`:

  ```
  Error: unsupported locales detected:
  UTF-8/UTF-8 \
  ```

- The option `nix.maxJobs` has been renamed to `nix.settings.max-jobs`

- Unbind a new Rofi keybind, otherwise Rofi doesn't start properly due
  to a keybind conflict.

- Comment out the installation of osc, it doesn't build on NixOS 22.11